add_newline = true

[aws]
disabled = true

[battery]
disabled = true

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[cmd_duration]

[conda]

[directory]
truncation_length = 3

[dotnet]
disabled = true

[env_var]
disabled = true

[elm]
symbol = " "

[git_branch]
symbol = "󰘬 "

[git_commit]
disabled = false
commit_hash_length = 4
tag_disabled = false

[git_state]
disabled = true

[git_status]
conflicted = "="
untracked = "?"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"
stashed = "$"
ahead = "⇡"
behind = "⇣"
diverged = "⇕"

[golang]
symbol = " "

[hostname]

[jobs]

[kubernetes]
symbol = "⎈ "
disabled = true

[line_break]
disabled = false

[nix_shell]
disabled = true

[memory_usage]
disabled = true

[java]
symbol = " "

[julia]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = "󰏗 "

[python]
symbol = "󰌠 "

[ruby]

[rust]
symbol = " "

[time]
disabled = true

[username]
disabled = false
